Models/Agenda.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Agenda_GitHub.Models
{
    public class Agenda
    {
        public int AgendaID { get; set; }
        public string Anotacao { get; set; }
        public string Data { get; set; }


    }
}

Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;

namespace Agenda_GitHub.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
          : base(options)
        {

        }
        public DbSet<Agenda> Agendas { get; set; }
    }
}

Models/EFAgendaRepositorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace Agenda_GitHub.Models
{
    public class EFAgendaRepositorio : IAgendaRepositorio
    {
        public ApplicationDbContext context;

        public EFAgendaRepositorio(ApplicationDbContext ctx)
        {
            context = ctx;
        }
        public IQueryable<Agenda> Agendas => context.Agendas;

        public void Create(Agenda agenda)
        {
            context.Add(agenda);
            context.SaveChanges();
        }

        public Agenda ObterAgenda(int id)
        {
            var agenda = context.Agendas
            .FirstOrDefault(a => a.AgendaID == id);
            return agenda;
        }
        public void Edit(Agenda agenda)
        {
            context.Entry(agenda).State = EntityState.Modified;
            context.SaveChanges();
        }
        public void Delete(Agenda agenda)
        {
            context.Remove(agenda);
            context.SaveChanges();
        }

    }
}

Models/ErrorViewModel.cs
using System;

namespace Agenda_GitHub.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IAgendaRepositorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Agenda_GitHub.Models
{
    public interface IAgendaRepositorio
    {
        IQueryable<Agenda> Agendas { get; }
        public void Create(Agenda agenda);
        public Agenda ObterAgenda(int id);
        public void Edit(Agenda agenda);
        public void Delete(Agenda agenda);
    }
}

Models/SeedData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Builder;

namespace Agenda_GitHub.Models
{
    public class SeedData
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            ApplicationDbContext context = app.ApplicationServices.GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();

            if (!context.Agendas.Any())
            {
                context.Agendas.AddRange(
                    new Agenda
                    {
                        Anotacao = "Consulta com Doutor Fidelis",
                        Data = "20/04/2021"
                    },
                    new Agenda
                    {
                        Anotacao = "Consulta com Dentista",
                        Data = "15/07/2021"
                    }
                    );
                context.SaveChanges();
            }
        }

    }
}

Models/Teste.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Agenda_GitHub.Models
{
    public class Teste
    {
        int x;
    }
}

Models/ViewModels/AgendaListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda_GitHub.Models;

namespace Agenda_GitHub.Models.ViewModels
{
    public class AgendaListViewModel
    {
        public IEnumerable<Agenda> Agendas { get; set; }

    }
}

Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Agenda_GitHub.Models.ViewModels;
using Agenda_GitHub.Models;

namespace Agenda_GitHub.Controllers
{
    public class AgendaController : Controller
    {
        private ApplicationDbContext _context;
        private IAgendaRepositorio repositorio;
        public int PageSize = 2;

        public AgendaController(IAgendaRepositorio repo, ApplicationDbContext ctx)
        {
            repositorio = repo;
            _context = ctx;
        }

        public ViewResult List(int pagina = 1) =>
           View(new AgendaListViewModel
           {
               Agendas = repositorio.Agendas
               .OrderBy(p => p.AgendaID)
           });

       
        public async Task<IActionResult> Index()
        {
            return View(await _context.Agendas.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        public IActionResult Create([Bind("AgendaID,Anotacao,Data")] Agenda agenda)
        {
            repositorio.Create(agenda);
            return RedirectToAction("List");
        }

        public IActionResult Details(int id)
        {
            var agenda = repositorio.ObterAgenda(id);
            return View(agenda);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var agenda = _context.Agendas.Find(id);
            return View(agenda);
        }
        [HttpPost]
        public IActionResult Edit(Agenda agenda)
        {
            repositorio.Edit(agenda);
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var agenda = repositorio.ObterAgenda(id);
            return View(agenda);
        }
        [HttpPost]
        public IActionResult Delete(Agenda agenda)
        {
            repositorio.Delete(agenda);
            return RedirectToAction("List");
        }

    }
}

Controllers/HomeController.cs
using Agenda_GitHub.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Agenda_GitHub.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Agenda/Create.cshtml
@model Agenda_GitHub.Models.Agenda

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Agenda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Anotacao" class="control-label"></label>
                <input asp-for="Anotacao" class="form-control" />
                <span asp-validation-for="Anotacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Voltar para a Lista</a>
</div>

Views/Agenda/Delete.cshtml
@model Agenda_GitHub.Models.Agenda

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Excluir</h1>

<h3>Você realmente quer apagar a anotação abaixo?</h3>
<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anotacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anotacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AgendaID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Voltar a Lista</a>
    </form>
</div>

Views/Agenda/Details.cshtml
@model Agenda_GitHub.Models.Agenda

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalhes</h1>

<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anotacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anotacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AgendaID">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.AgendaID">Excluir</a> |
    <a asp-action="List">Voltar a Lista</a>
</div>

Views/Agenda/Edit.cshtml
@model Agenda_GitHub.Models.Agenda

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Agenda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AgendaID" />
            <div class="form-group">
                <label asp-for="Anotacao" class="control-label"></label>
                <input asp-for="Anotacao" class="form-control" />
                <span asp-validation-for="Anotacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Voltar a Lista</a>
</div>

Views/Agenda/List.cshtml
@model Agenda_GitHub.Models.ViewModels.AgendaListViewModel

<a asp-action="Create">Adicionar Nova Anotaçao</a>
@foreach (var item in Model.Agendas)
{
    <tr>
        <td>
            <h4>@item.Anotacao </h4>
            <h4>@item.Data </h4>
        </td>


    </tr>
    <div>

        <a asp-action="Edit" asp-route-id="@item.AgendaID">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.AgendaID">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.AgendaID">Delete</a>

    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda_GitHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agenda_GitHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="List">Ver Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Agenda_GitHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>